### ISSUE TITLE
Apache 2.4 install is broken on Centos

### ISSUE THREAD

**Issue by cazino** [scality/openstack-ci-scripts#19]
Since https://github.com/scality/openstack-ci-scripts/pull/17/, one can choose to use Apache 2.4 in front of Sproxyd on Centos.

This setup is not working properly : try running `wget  http://localhost:81/proxy/chord_path/.conf` and you bill get a 0 bytes length response.

Before fixing this we should fix the way we test the validity of the installation, as the Jenkins job did not detect this : https://37.187.159.67:5443/job/ring-install-test/48/

**Comment by cazino** [comment]
Some more details : the service responds on every possible request with a 0 bytes length response (not even a header).
Requests are logged in the Apache log file but nothing in Sproxyd logs.

**Comment by NicolasT** [comment]
Can it serve static files?

**Comment by cazino** [comment]
Oups. Actually there are some headers in the response.
Responses are 200's , but without response body.
Static files work fine.

**Comment by NicolasT** [comment]
Any headers coming from sproxyd, or generic Apache stuff?

**Comment by cazino** [comment]
Only Apache headers and nothing in Sproxyd logs, it feels like Sproxyd never gets any request but if Sproxyd is not running then the responses are 503.
